name: Build Test
on:
  push:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        name: Checkout
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run test and building
        run: ./mvnw clean test compile war:war
      - run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging