name: Deploy workflow
run-name: Deploy workflow 
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        name: Checkout
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run test and building
        run: ./mvnw clean test compile war:war
      - run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: staging
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: abctechapi
          environment_name: Abctechapi-env
          version_label: ${{ github.ref_name }}-R${{ github.run_id }}-V${{ github.run_number }}
          region: us-east-1
          deployment_package: ./staging/Package/abctechapi-0.0.2-SNAPSHOT.war